OnlineStore/src/OnlineStore.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineStore.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

OnlineStore/src/OnlineStore.Web/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Core;
using OnlineStore.Core.Entities;
using OnlineStore.SharedKernel.Interfaces;
using OnlineStore.Web.ApiModels;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineStore.Web.Controllers
{
    public class ToDoController : Controller
    {
        private readonly IRepository _repository;

        public ToDoController(IRepository repository)
        {
            _repository = repository;
        }

        public async Task<IActionResult> Index()
        {
            var items = (await _repository.ListAsync<ToDoItem>())
                            .Select(ToDoItemDTO.FromToDoItem);
            return View(items);
        }

        public IActionResult Populate()
        {
            int recordsAdded = DatabasePopulator.PopulateDatabase(_repository);
            return Ok(recordsAdded);
        }
    }
}

OnlineStore/src/OnlineStore.Web/Pages/ToDoRazorPage/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using OnlineStore.Core.Entities;
using OnlineStore.SharedKernel.Interfaces;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace OnlineStore.Web.Pages.ToDoRazorPage
{
    public class IndexModel : PageModel
    {
        private readonly IRepository _repository;

        public List<ToDoItem> ToDoItems { get; set; }

        public IndexModel(IRepository repository)
        {
            _repository = repository;
        }

        public async Task OnGetAsync()
        {
            ToDoItems = await _repository.ListAsync<ToDoItem>();
        }
    }
}

OnlineStore/src/OnlineStore.Web/Pages/ToDoRazorPage/Populate.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using OnlineStore.Core;
using OnlineStore.SharedKernel.Interfaces;

namespace OnlineStore.Web.Pages.ToDoRazorPage
{
    public class PopulateModel : PageModel
    {
        private readonly IRepository _repository;

        public PopulateModel(IRepository repository)
        {
            _repository = repository;
        }

        public int RecordsAdded { get; set; }

        public void OnGet()
        {
            RecordsAdded = DatabasePopulator.PopulateDatabase(_repository);
        }
    }
}

OnlineStore/src/OnlineStore.Web/Pages/ToDoRazorPage/Index.cshtml
@page
@model OnlineStore.Web.Pages.ToDoRazorPage.IndexModel

<h2>To Do Items (Razor Page)</h2>
<ul>
    @foreach (var item in Model.ToDoItems)
    {
        <li>@item.Title<br />@item.Description</li>
    }
</ul>

OnlineStore/src/OnlineStore.Web/Pages/ToDoRazorPage/Populate.cshtml
@page
@model OnlineStore.Web.Pages.ToDoRazorPage.PopulateModel
<h3>Records Added: @Model.RecordsAdded</h3>
<p>
    <a asp-page="Index">Check them out!</a>
</p>

OnlineStore/src/OnlineStore.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Clean DDD Architecture Sample";
}

<div class="row">
    <div class="col-md-6">
        <h2>To Do Items (MVC)</h2>
        <ul>
            <li><a asp-area="" asp-controller="ToDo" asp-action="Populate">Load Sample To Do Items</a> (API call returning just a number)</li>
            <li><a asp-area="" asp-controller="ToDo" asp-action="Index">List To Do Items</a></li>
            <li><a href="/swagger">API Documentation (Swagger)</a></li>
        </ul>
        <h2>To Do Items (Razor Pages)</h2>
        <ul>
            <li><a asp-page="/ToDoRazorPage/Populate">Load Sample To Do Items</a></li>
            <li><a asp-page="/ToDoRazorPage/Index">List To Do Items</a></li>
        </ul>
    </div>
    <div class="col-md-6">
        <h2>About the Author</h2>
        <ul>
            <li><a href="https://ardalis.com">Blog - Ardalis.com</a></li>
            <li><a href="https://twitter.com/ardalis">Twitter - @@ardalis</a></li>
            <li><a href="https://github.com/ardalis">GitHub</a></li>
        </ul>
    </div>
</div>

OnlineStore/src/OnlineStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineStore.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">OnlineStore.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - OnlineStore.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.2.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

@await RenderSectionAsync("scripts", required: false).ConfigureAwait(false)
</body>
</html>

OnlineStore/src/OnlineStore.Web/Views/ToDo/Index.cshtml
@{
    ViewData["Title"] = "ToDo List";
}
@model IEnumerable<OnlineStore.Web.ApiModels.ToDoItemDTO>
<h2>To Do Items (MVC View)</h2>
<ul>
@foreach (var item in Model)
{
    <li>@item.Title<br/>@item.Description</li>
}
</ul>